version: '3'

services:

  billing_db: 
    image: mysql:8.0.26
    ports:
      - 5000:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345


  billing_app:
    restart: always

    volumes:
      - ./in:/in
      - ./app:/src/app
    build: .
    ports:
      - 8080:5000
    depends_on:
      - "billing_db"
